{% set name = "bert-extractive-summarizer" %}
{% set python_min = "3.8" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dmmiller612/bert-extractive-summarizer/archive/{{ version }}.tar.gz
  sha256: 4bfc5384c9411d3b02501d007087827125dadb42ce0c39333e609bdb91c9f3c4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - transformers
    - scikit-learn
    - spacy

test:
  imports:
    - summarizer
    - tests
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
# Tests Only
    - scikit-learn
    - spacy
    - transformers
    - pytorch-cpu

about:
  home: https://github.com/dmmiller612/bert-extractive-summarizer
  summary: Easy to use extractive text summarization with BERT 
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
